

const deleteUser = async (req,res) => {
    try {
        
    } catch (err) {
        res.status(500).json({ message: "Something went wrong" });
    }
}

export default deleteUser;